### ISSUE TITLE
Crash if ~/.unfollow is missing 

### ISSUE THREAD

**Issue by Dinoosawruss** [TechWiz-3/who-unfollowed-me#39]
If you delete `~/.unfollow`, the program appears to crash

Happy to work on a fix for this

**Comment by TechWiz-3** [comment]
That's really weird. What's the error?

**Comment by Dinoosawruss** [comment]
It's a FileNotFoundError which is raised "when you are trying to access a file or a directory that doesn't exist"

So think `get_config()` just needs a `os.path.isdir` check and if it doesn't create the directory

**Comment by TechWiz-3** [comment]
What's the full traceback? I assume it's happening from `cli.py` when getting the config cecause `get_user()` has that feature already https://github.com/TechWiz-3/who-unfollowed-me/blob/main/unfollow/unfollow.py#L46

**Comment by Dinoosawruss** [comment]
```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\mdorm\onedrive\documents\code\python\who-unfollowed-me\unfollow\cli.py", line 17, in <module>
    config = get_config()
  File "C:\Users\mdorm\onedrive\documents\code\python\who-unfollowed-me\unfollow\config.py", line 290, in get_config
    with open(f"{UNFOLLOW_PATH}/unfollow.toml", "w", encoding='utf-8') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mdorm/.unfollow/unfollow.toml'
```

**Comment by Dinoosawruss** [comment]
Should be fixed in #41

**Comment by donno2048** [comment]
Actually this is still an issue, on Pydroid I get the same error which disappears after 
```sh
$ mkdir ~/.unfollow
```

**Comment by TechWiz-3** [comment]
Hmm

**Comment by TechWiz-3** [comment]
Could you please show the full error traceback?

**Comment by donno2048** [comment]
```py
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/ru.iiec.pydroid3/app_HOME/.unfollow/unfollow.toml'
```
(In Pydroid `~` is `/data/user/0/ru.iiec.pydroid3/app_HOME/`)

**Comment by TechWiz-3** [comment]
Hmm, I'm quite confused as to why this would happen, you're sure you're using the latest version?

IF you are, could you please remove/delete the directory you created then open an interactive Python shell and try:

```py
import os
os.path.exists(os.path.expanduser("~/.unfollow"))
```
And send output, whether it was True or False

**Comment by donno2048** [comment]
```py
/storage/emulated/0 $ pip list | grep unfollow
unfollow           3.0.0
/storage/emulated/0 $ python
Python 3.9.7 (default, Oct  9 2021, 08:02:40)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.exists(os.path.expanduser("~/.unfollow"))
False
>>>
```

**Comment by TechWiz-3** [comment]
Ok please do `pip install -U unfollow`

Ensure your version is `5.0.0`. The issue should be fixed

**Comment by donno2048** [comment]
Well, now I get this


```py
...
    from unfollow.cli import main
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/unfollow/cli.py", line 17, in <module>
    config = get_config()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/unfollow/config.py", line 683, in get_config
    config = toml.loads(default_config)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/toml/decoder.py", line 478, in loads
    raise TomlDecodeError("What? " + group +
toml.decoder.TomlDecodeError: What? bubbles already exists?{'simple': {'welcome_message': 'Welcome to who-unfollowed-me Python implementation by Zac the Wise', 'fetched_followers_message': 'Fetched github followers', 'no_unfollows_message': 'No unfollows!', 'end_message': 'You have {follower_num} followers. Keep up the good work\n', 'thankyou_message': 'Thanks for using this project'}, 'regular': {'welcome_message': ':dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]', 'fetched_followers_message': '[green]✔ [underline]Fetched github followers', 'last_week_unfollowers': '[purple]✔ [underline]Unfollowers from last week', 'no_unfollows_message': '[green]:raised_hands: [underline]No unfollows!', 'end_message': ':fire: You have {follower_num} followers. Keep up the good work\n', 'thankyou_message': ':pray: Thanks for using this project'}, 'panels': {'welcome_message': ':dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]', 'fetched_followers_message': '[green]✔ [underline]Fetched github followers', 'last_week_unfollowers': '[purple]✔ [underline]Unfollowers from last week', 'no_unfollows_message': '[white on #308012] No unfollows! [/white on #308012]                                ', 'end_message': ':fire: You have {follower_num} followers. Keep up the good work\n', 'thankyou_message': ':pray: Thanks for using this project'}, 'bubbles': {'welcome_message_a': '[white on purple]Welcome to[/white on purple]', 'welcome_message_b': '[white on red]who-unfollowed-me[/white on red]', 'welcome_message_c': '[white on blue]the Python implementation[/white on blue]', 'welcome_message_d': '[white on dark_goldenrod]by Zac the Wise[/white on dark_goldenrod]', 'fetched_followers_message': '[white on cyan]Fetched github followers[/white on cyan]', 'last_week_unfollowers': '[purple]✔ [underline]Unfollowers from last week', 'no_unfollows_message': '[white on green4]No unfollows![/white on green4]', 'end_message_a': '[white on purple]You have {follower_num} followers.[/white on purple]', 'end_message_b': '[white on magenta]Keep up the good work![/white on magenta]', 'thankyou_message': '[white on blue]Thanks for using this project[/white on blue]'}} (line 380 column 1 char 23604)
```

**Comment by TechWiz-3** [comment]
delete `.unfollow` directory then run again

**Comment by donno2048** [comment]
Same result

**Comment by TechWiz-3** [comment]
That's really weird, any ideas @Dinoosawruss?

**Comment by Dinoosawruss** [comment]
> Same result 

Could you send the error traceback just incase it's not the same

Can't really think of why it's should be any different because ultimately it's still running Python 3.9.7

**Comment by TechWiz-3** [comment]
@donno2048 ^^

**Comment by donno2048** [comment]
```sh
/storage/emulated/0 $ unfollow
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/unfollow", line 5, in <module>
    from unfollow.cli import main
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/unfollow/cli.py", line 26, in <module>
    handled_version = config_version_handle(0)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/unfollow/config.py", line 697, in config_version_handle
    _ = get_config(overwrite=True)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/unfollow/config.py", line 677, in get_config
    config = toml.loads(default_config)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/toml/decoder.py", line 478, in loads
    raise TomlDecodeError("What? " + group +
toml.decoder.TomlDecodeError: What? bubbles already exists?{'simple': {'welcome_message': 'Welcome to who-unfollowed-me Python implementation by Zac the Wise', 'fetched_followers_message': 'Fetched github followers', 'no_unfollows_message': 'No unfollows!', 'end_message': 'You have {follower_num} followers. Keep up the good work\n', 'thankyou_message': 'Thanks for using this project'}, 'regular': {'welcome_message': ':dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]', 'fetched_followers_message': '[green]✔ [underline]Fetched github followers', 'last_week_unfollowers': '[purple]✔ [underline]Unfollowers from last week', 'no_unfollows_message': '[green]:raised_hands: [underline]No unfollows!', 'end_message': ':fire: You have {follower_num} followers. Keep up the good work\n', 'thankyou_message': ':pray: Thanks for using this project'}, 'panels': {'welcome_message': ':dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]', 'fetched_followers_message': '[green]✔ [underline]Fetched github followers', 'last_week_unfollowers': '[purple]✔ [underline]Unfollowers from last week', 'no_unfollows_message': '[white on #308012] No unfollows! [/white on #308012]                                ', 'end_message': ':fire: You have {follower_num} followers. Keep up the good work\n', 'thankyou_message': ':pray: Thanks for using this project'}, 'bubbles': {'welcome_message_a': '[white on purple]Welcome to[/white on purple]', 'welcome_message_b': '[white on red]who-unfollowed-me[/white on red]', 'welcome_message_c': '[white on blue]the Python implementation[/white on blue]', 'welcome_message_d': '[white on dark_goldenrod]by Zac the Wise[/white on dark_goldenrod]', 'fetched_followers_message': '[white on cyan]Fetched github followers[/white on cyan]', 'last_week_unfollowers': '[purple]✔ [underline]Unfollowers from last week', 'no_unfollows_message': '[white on green4]No unfollows![/white on green4]', 'end_message_a': '[white on purple]You have {follower_num} followers.[/white on purple]', 'end_message_b': '[white on magenta]Keep up the good work![/white on magenta]', 'thankyou_message': '[white on blue]Thanks for using this project[/white on blue]'}} (line 380 column 1 char 23604)
/storage/emulated/0 $
```

**Comment by Dinoosawruss** [comment]
Can you send the config file please? @donno2048

**Comment by TechWiz-3** [comment]
The plot thickens 😂

**Comment by Dinoosawruss** [comment]
Any update @donno2048

**Comment by donno2048** [comment]
What config file?

**Comment by TechWiz-3** [comment]
> What config file?

`~/.unfollow/unfollow.toml`

**Comment by TechWiz-3** [comment]
I converted the dict from donno's traceback to a toml file and got this:
```toml
[simple]
welcome_message = "Welcome to who-unfollowed-me Python implementation by Zac the Wise"
fetched_followers_message = "Fetched github followers"
no_unfollows_message = "No unfollows!"
end_message = "You have {follower_num} followers. Keep up the good work\n"
thankyou_message = "Thanks for using this project"

[regular]
welcome_message = ":dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]"
fetched_followers_message = "[green]✔ [underline]Fetched github followers"
last_week_unfollowers = "[purple]✔ [underline]Unfollowers from last week"
no_unfollows_message = "[green]:raised_hands: [underline]No unfollows!"
end_message = ":fire: You have {follower_num} followers. Keep up the good work\n"
thankyou_message = ":pray: Thanks for using this project"

[panels]
welcome_message = ":dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]"
fetched_followers_message = "[green]✔ [underline]Fetched github followers"
last_week_unfollowers = "[purple]✔ [underline]Unfollowers from last week"
no_unfollows_message = "[white on #308012] No unfollows! [/white on #308012]                                "
end_message = ":fire: You have {follower_num} followers. Keep up the good work\n"
thankyou_message = ":pray: Thanks for using this project"

[bubbles]
welcome_message_a = "[white on purple]Welcome to[/white on purple]"
welcome_message_b = "[white on red]who-unfollowed-me[/white on red]"
welcome_message_c = "[white on blue]the Python implementation[/white on blue]"
welcome_message_d = "[white on dark_goldenrod]by Zac the Wise[/white on dark_goldenrod]"
fetched_followers_message = "[white on cyan]Fetched github followers[/white on cyan]"
last_week_unfollowers = "[purple]✔ [underline]Unfollowers from last week"
no_unfollows_message = "[white on green4]No unfollows![/white on green4]"
end_message_a = "[white on purple]You have {follower_num} followers.[/white on purple]"
end_message_b = "[white on magenta]Keep up the good work![/white on magenta]"
thankyou_message = "[white on blue]Thanks for using this project[/white on blue]"
```

**Comment by Dinoosawruss** [comment]
Can't see anything there but would still be nice to get the full file

**Comment by Dinoosawruss** [comment]
@donno2048 any update?

**Comment by donno2048** [comment]
> > What config file?
> 
> `~/.unfollow/unfollow.toml`

It's empty

**Comment by Dinoosawruss** [comment]
Even if you delete the file and rerun?

**Comment by donno2048** [comment]
Yes

**Comment by TechWiz-3** [comment]
What version are you on now?

**Comment by donno2048** [comment]
> Ok please do `pip install -U unfollow`
> 
> Ensure your version is `5.0.0`. The issue should be fixed

...

**Comment by Dinoosawruss** [comment]
Can you delete the `~/.unfollow` directory, rerun the program and see if anything is created?

**Comment by Dinoosawruss** [comment]
Diagnosis:

I ran a couple of things in Pydroid on Bluestacks and found that `/data/user/0/ru.iiec.pydroid3/app_HOME` seems to be the home directory when running in Pydroid
![image](https://user-images.githubusercontent.com/22278485/204890350-6402ec12-7316-4119-8e20-b3a1f5be6ef1.png)

I tried to create a file here to test if we can, which worked
![image](https://user-images.githubusercontent.com/22278485/204890509-b4011f80-e338-4838-a803-98ee472e0255.png)
It did

I ran an `ls -a` against the home dir and found that `.unfollow`and `unfollow.toml` were created
![image](https://user-images.githubusercontent.com/22278485/204890815-ac6cfa3d-b818-4c94-84d4-03fa3ba7539a.png)
![image](https://user-images.githubusercontent.com/22278485/204890840-cd640097-f055-42f6-a290-f57d687d1fa5.png)

I noticed that the error was complaining about line 380 of `unfollow.toml` so checked this and it seems we have some invalid toml which is ultimately causing the issue
![image](https://user-images.githubusercontent.com/22278485/204891314-a887cc68-0d07-43e8-935a-5625d388211e.png)

I will commit this change and PR it and hopefully, that will fix the issue.
Quite unsure why this doesn't also happen on Windows/other Linux OSs but have struggled to recreate it outside of Pydroid

I cannot test this fix as have no way of running the full code on Pydroid but am assuming that this is the cause

**Comment by Dinoosawruss** [comment]
See #67

**Comment by Dinoosawruss** [comment]
Hey @donno2048 just checking that PR fixed the issue you were having?

**Comment by TechWiz-3** [comment]
Remember to update to version `5.0.1`

**Comment by Dinoosawruss** [comment]
![image](https://user-images.githubusercontent.com/22278485/206542727-c8e02687-82e2-4fb8-95fc-426d51476c23.png)
The error appears to be gone on BlueStacks

**Comment by donno2048** [comment]
> Hey @donno2048 just checking that PR fixed the issue you were having?

Yes!

**Comment by TechWiz-3** [comment]
🥳 thanks guys
